name: CI

on:
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Build rust
        run: npm run build --rust
      - name: Typecheck
        run: npm run typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Install playwright
        run: npx playwright install
      - name: Test
        run: npm run e2e
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Lint
        run: npm run lint:eslint
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Lint
        run: npm run lint:rustfmt
