name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: yarn install
      - name: Build
        run: yarn build
      - name: Typecheck
        run: yarn typecheck
      - name: Copy dist directory to remove host
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./dist/*"
          target: "~/dist"
          rm: true
      - name: Deploy
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.SSH_KEY }}" > $TEMP
          ssh -o 'StrictHostKeyChecking no' -i $TEMP ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p${{ secrets.SSH_PORT }} 'bash -s' < scripts/deploy.sh
          rm -f $TEMP
