name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Build rust
        run: npm run build --rust
      - name: Typecheck
        run: npm run typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test

  deploy:
    needs: [typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          rustup toolchain install nightly-2023-06-15-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-06-15-x86_64-unknown-linux-gnu
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Copy dist directory to remote host
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: './dist/*'
          target: '~/dist/'
          rm: true
      - name: Deploy
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.SSH_KEY }}" > $TEMP
          ssh -o 'StrictHostKeyChecking no' -i $TEMP ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p${{ secrets.SSH_PORT }} 'bash -s' < scripts/deploy.sh
          rm -f $TEMP
