name: Typecheck

on:
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Typecheck
        run: |
          yarn install
          yarn build
          yarn typecheck
